// const obj = {
//     //key     value      = property
//     "first name" : "Raj",
//     lname : "Shah",
//     age : 23
// };
// console.log(obj);
// - Dot vs Bracket Notation.
// console.log(obj.fname);
// console.log(obj["fname"]);

// console.log(obj["first name"]);  // raj
// console.log(obj."first name");  // error


// basic for loop :    doesn't working with Object
// for (let index = 0; index < array.length; index++) {
//     const element = array[index];
    
// }

// for of loop :  doesn't working with Object
// for (const element of obj) {
//     console.log(element);
// }

// for each loop : doesn't working with Object
// obj.forEach(element => {
//    console.log(element);
// });


// How to Access Keys of Given Object  :
// for in loop :  working with Object

// for (let key in obj) {
//     // console.log(key,obj.key);
//     console.log(key,obj[key]);
// }

// const obj = {
//     //key     value      = property
//     "first name" : "Raj",
//     lname : "Shah",
//     123 : 23
// };
// console.log(obj);
// - Iterate objects. 

// for (const data1 in obj) {
//     console.log(data1,":",obj[data1]);
// }

// for (const key in obj) {
//     console.log(key,typeof key);
//     console.log(obj[key],typeof obj[key]);

// }

// any Key :  type => string 
// values : type  => anuthing 

// - Computed properties.   []

// {
//   Name : "Raj",
//   Email : "R@gmail.com"
// // }
// var key1 = "Name";
// var key2 = "Email";
// var value1 = "Raj";
// var value2  = "R@gmail.com";
// const p1 = {
//     [key1] : value1,
//     key2 : value2
// };           
//   //   
/*   //
//
*/  //
//            // console.log(p1); 
//            // console.log(p1); 
//            // console.log(p1); 
//            // 
//            //   
/*          
Iterate objects : 
Car Object : 
    Model 
    Price 
    Fuel 

*/   

/*
Using Computed properties : 

Emplyee Object : 
    Name : 
    Salary : 
    Position :

*/ 

